version: "3.9"  # optional since v1.27.0
services:
  scraping:
    image: hackergy/volt-box-scraping:latest
    ports:
      - "8080:8080"

  mongodb_container:
    image: mongo:5.0.3-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
