version: "3.9"  # optional since v1.27.0
services:
  scraping:
    image: hackergy/volt-box-scraping:latest
    ports:
      - "8080:8080"
  postgres:
    image: postgres:13.3-alpine3.14
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: voltbox
      POSTGRES_USER: voltbox
      POSTGRES_PASSWORD: voltbox
volumes:
  postgres-data:
