version: "3.9"  # optional since v1.27.0
services:
  scraping:
    image: hackergy/volt-box-scraping:latest
    depends_on:
    - "mongodb_container"

  enriching:
    image: hackergy/volt-box-enriching:latest
    depends_on:
      - "mongodb_container"

  rest-api:
    image: hackergy/volt-box-rest-api:latest
    depends_on:
      - "mongodb_container"
    ports:
      - "6084:8080"

  frontend:
    image: hackergy/frontend:latest
    ports:
      - "6083:80"

  mongodb_container:
    image: mongo:5.0.3-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    container_name: mongodb

volumes:
  mongodb_data_container:
